// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AckType int32

const (
	Ack_EXCEPTION AckType = 0
	Ack_FAIL      AckType = 1
	Ack_SUCCESS   AckType = 2
)

// Enum value maps for AckType.
var (
	AckType_name = map[int32]string{
		0: "EXCEPTION",
		1: "FAIL",
		2: "SUCCESS",
	}
	AckType_value = map[string]int32{
		"EXCEPTION": 0,
		"FAIL":      1,
		"SUCCESS":   2,
	}
)

func (x AckType) Enum() *AckType {
	p := new(AckType)
	*p = x
	return p
}

func (x AckType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto_proto_enumTypes[0].Descriptor()
}

func (AckType) Type() protoreflect.EnumType {
	return &file_proto_proto_proto_enumTypes[0]
}

func (x AckType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckType.Descriptor instead.
func (AckType) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{3, 0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{0}
}

type Bid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BidAmount     int32                  `protobuf:"varint,2,opt,name=bidAmount,proto3" json:"bidAmount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bid) Reset() {
	*x = Bid{}
	mi := &file_proto_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{1}
}

func (x *Bid) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bid) GetBidAmount() int32 {
	if x != nil {
		return x.BidAmount
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HighestBid    int32                  `protobuf:"varint,2,opt,name=highestBid,proto3" json:"highestBid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_proto_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Result) GetHighestBid() int32 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{3}
}

type Outcome struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*Outcome_HighestBid
	//	*Outcome_Result
	Type          isOutcome_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outcome) Reset() {
	*x = Outcome{}
	mi := &file_proto_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outcome) ProtoMessage() {}

func (x *Outcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outcome.ProtoReflect.Descriptor instead.
func (*Outcome) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{4}
}

func (x *Outcome) GetType() isOutcome_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Outcome) GetHighestBid() int32 {
	if x != nil {
		if x, ok := x.Type.(*Outcome_HighestBid); ok {
			return x.HighestBid
		}
	}
	return 0
}

func (x *Outcome) GetResult() *Result {
	if x != nil {
		if x, ok := x.Type.(*Outcome_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isOutcome_Type interface {
	isOutcome_Type()
}

type Outcome_HighestBid struct {
	HighestBid int32 `protobuf:"varint,1,opt,name=highestBid,proto3,oneof"`
}

type Outcome_Result struct {
	Result *Result `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*Outcome_HighestBid) isOutcome_Type() {}

func (*Outcome_Result) isOutcome_Type() {}

var File_proto_proto_proto protoreflect.FileDescriptor

const file_proto_proto_proto_rawDesc = "" +
	"\n" +
	"\x11proto/proto.proto\"\a\n" +
	"\x05Empty\"3\n" +
	"\x03Bid\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1c\n" +
	"\tbidAmount\x18\x02 \x01(\x05R\tbidAmount\"8\n" +
	"\x06Result\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1e\n" +
	"\n" +
	"highestBid\x18\x02 \x01(\x05R\n" +
	"highestBid\"3\n" +
	"\x03Ack\",\n" +
	"\x04type\x12\r\n" +
	"\tEXCEPTION\x10\x00\x12\b\n" +
	"\x04FAIL\x10\x01\x12\v\n" +
	"\aSUCCESS\x10\x02\"V\n" +
	"\aOutcome\x12 \n" +
	"\n" +
	"highestBid\x18\x01 \x01(\x05H\x00R\n" +
	"highestBid\x12!\n" +
	"\x06result\x18\x02 \x01(\v2\a.ResultH\x00R\x06resultB\x06\n" +
	"\x04type2;\n" +
	"\x04Node\x12\x14\n" +
	"\x06TryBid\x12\x04.Bid\x1a\x04.Ack\x12\x1d\n" +
	"\tTryResult\x12\x06.Empty\x1a\b.Outcome2>\n" +
	"\aAuction\x12\x14\n" +
	"\x06TryBid\x12\x04.Bid\x1a\x04.Ack\x12\x1d\n" +
	"\tTryResult\x12\x06.Empty\x1a\b.OutcomeB\tZ\a./protob\x06proto3"

var (
	file_proto_proto_proto_rawDescOnce sync.Once
	file_proto_proto_proto_rawDescData []byte
)

func file_proto_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_proto_rawDesc), len(file_proto_proto_proto_rawDesc)))
	})
	return file_proto_proto_proto_rawDescData
}

var file_proto_proto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_proto_proto_goTypes = []any{
	(AckType)(0),    // 0: Ack.type
	(*Empty)(nil),   // 1: Empty
	(*Bid)(nil),     // 2: Bid
	(*Result)(nil),  // 3: Result
	(*Ack)(nil),     // 4: Ack
	(*Outcome)(nil), // 5: Outcome
}
var file_proto_proto_proto_depIdxs = []int32{
	3, // 0: Outcome.result:type_name -> Result
	2, // 1: Node.TryBid:input_type -> Bid
	1, // 2: Node.TryResult:input_type -> Empty
	2, // 3: Auction.TryBid:input_type -> Bid
	1, // 4: Auction.TryResult:input_type -> Empty
	4, // 5: Node.TryBid:output_type -> Ack
	5, // 6: Node.TryResult:output_type -> Outcome
	4, // 7: Auction.TryBid:output_type -> Ack
	5, // 8: Auction.TryResult:output_type -> Outcome
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_proto_proto_init() }
func file_proto_proto_proto_init() {
	if File_proto_proto_proto != nil {
		return
	}
	file_proto_proto_proto_msgTypes[4].OneofWrappers = []any{
		(*Outcome_HighestBid)(nil),
		(*Outcome_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_proto_rawDesc), len(file_proto_proto_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_proto_depIdxs,
		EnumInfos:         file_proto_proto_proto_enumTypes,
		MessageInfos:      file_proto_proto_proto_msgTypes,
	}.Build()
	File_proto_proto_proto = out.File
	file_proto_proto_proto_goTypes = nil
	file_proto_proto_proto_depIdxs = nil
}
